---
name: CI checks
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          ./test.bat
        shell: cmd
  xcop-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/xcop-action@master
  pdd-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/pdd-action@master
